-- Reelarc Footage, Phase 1: the tables behind uploads and proxies.
--
-- Adds four new tables (footage_members, footage_projects, footage_files,
-- footage_proxy_jobs) and one database login, footage_app, that the footage app
-- and proxy worker use. footage_app can read and write these four tables and
-- nothing else, so the backend's own tables stay out of its reach.
-- Row-level security is on for every new table, and Supabase's public API
-- (anon/authenticated) gets no access to them at all.
-- Nothing existing is altered, renamed or dropped. It all runs as one
-- transaction: if any statement fails, nothing changes.

CREATE ROLE "footage_app" WITH LOGIN NOINHERIT;--> statement-breakpoint
ALTER ROLE "footage_app" SET statement_timeout = '60s';--> statement-breakpoint
CREATE TABLE "footage_files" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "footage_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" bigint NOT NULL,
	"card" text DEFAULT '' NOT NULL,
	"path" text NOT NULL,
	"storage_key" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"last_modified_ms" bigint,
	"is_video" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"problem" text,
	"upload_id" text,
	"uploaded_at" timestamp with time zone,
	"uploaded_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "footage_files_storage_key_unique" UNIQUE("storage_key"),
	CONSTRAINT "footage_files_status_valid" CHECK ("footage_files"."status" in ('pending', 'uploading', 'uploaded', 'unreadable')),
	CONSTRAINT "footage_files_size_valid" CHECK ("footage_files"."size_bytes" >= 0)
);
--> statement-breakpoint
ALTER TABLE "footage_files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "footage_members" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "footage_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"role" text DEFAULT 'admin' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "footage_members_email_unique" UNIQUE("email"),
	CONSTRAINT "footage_members_email_lowercase" CHECK ("footage_members"."email" = lower("footage_members"."email")),
	CONSTRAINT "footage_members_role_valid" CHECK ("footage_members"."role" in ('admin', 'editor', 'social'))
);
--> statement-breakpoint
ALTER TABLE "footage_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "footage_projects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "footage_projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1001 CACHE 1),
	"name" text NOT NULL,
	"shoot_date" date NOT NULL,
	"storage_prefix" text NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"uploaded_at" timestamp with time zone,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "footage_projects_storage_prefix_unique" UNIQUE("storage_prefix"),
	CONSTRAINT "footage_projects_status_valid" CHECK ("footage_projects"."status" in ('scheduled', 'uploading', 'uploaded', 'delivered', 'purged'))
);
--> statement-breakpoint
ALTER TABLE "footage_projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "footage_proxy_jobs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "footage_proxy_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"raw_key" text NOT NULL,
	"proxy_key" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 4 NOT NULL,
	"run_after" timestamp with time zone DEFAULT now() NOT NULL,
	"locked_by" text,
	"locked_at" timestamp with time zone,
	"progress" real,
	"error" text,
	"proxy_size_bytes" bigint,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "footage_proxy_jobs_file_id_unique" UNIQUE("file_id"),
	CONSTRAINT "footage_proxy_jobs_proxy_key_unique" UNIQUE("proxy_key"),
	CONSTRAINT "footage_proxy_jobs_status_valid" CHECK ("footage_proxy_jobs"."status" in ('queued', 'running', 'done', 'failed', 'skipped'))
);
--> statement-breakpoint
ALTER TABLE "footage_proxy_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "footage_files" ADD CONSTRAINT "footage_files_project_id_footage_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."footage_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "footage_proxy_jobs" ADD CONSTRAINT "footage_proxy_jobs_file_id_footage_files_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."footage_files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "footage_proxy_jobs" ADD CONSTRAINT "footage_proxy_jobs_project_id_footage_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."footage_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "footage_files_project_path_idx" ON "footage_files" USING btree ("project_id","path");--> statement-breakpoint
CREATE INDEX "footage_files_project_card_idx" ON "footage_files" USING btree ("project_id","card");--> statement-breakpoint
CREATE INDEX "footage_projects_shoot_date_idx" ON "footage_projects" USING btree ("shoot_date");--> statement-breakpoint
CREATE INDEX "footage_proxy_jobs_queue_idx" ON "footage_proxy_jobs" USING btree ("status","run_after");--> statement-breakpoint
CREATE INDEX "footage_proxy_jobs_project_idx" ON "footage_proxy_jobs" USING btree ("project_id");--> statement-breakpoint
CREATE POLICY "footage_app_all" ON "footage_files" AS PERMISSIVE FOR ALL TO "footage_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "footage_app_all" ON "footage_members" AS PERMISSIVE FOR ALL TO "footage_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "footage_app_all" ON "footage_projects" AS PERMISSIVE FOR ALL TO "footage_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "footage_app_all" ON "footage_proxy_jobs" AS PERMISSIVE FOR ALL TO "footage_app" USING (true) WITH CHECK (true);--> statement-breakpoint
-- The app and worker only read and write rows in these four tables.
GRANT USAGE ON SCHEMA "public" TO "footage_app";--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "footage_members", "footage_projects", "footage_files", "footage_proxy_jobs" TO "footage_app";--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE "footage_members_id_seq", "footage_projects_id_seq", "footage_files_id_seq", "footage_proxy_jobs_id_seq" TO "footage_app";--> statement-breakpoint
-- No access through Supabase's public API, even if row-level security were ever switched off.
REVOKE ALL ON "footage_members", "footage_projects", "footage_files", "footage_proxy_jobs" FROM "anon", "authenticated";--> statement-breakpoint
-- Guy can sign in from day one; Phase 2 adds invites for everyone else.
INSERT INTO "footage_members" ("email", "role") VALUES ('guy@reelarc.com', 'admin');
