-- Loupe: every table behind accounts, uploads and proxies, in Loupe's own Supabase project.
--
-- Creates the tables and one database login, loupe_app, that the Loupe app and proxy worker use.
-- loupe_app can read and write these tables and nothing else. Row-level security is on for every
-- table, and Supabase's public API (anon/authenticated) gets no access to them at all.
-- It all runs as one transaction: if any statement fails, nothing changes.

CREATE ROLE "loupe_app" WITH LOGIN NOINHERIT;--> statement-breakpoint
ALTER ROLE "loupe_app" SET statement_timeout = '60s';--> statement-breakpoint
CREATE TABLE "loupe_accounts" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "loupe_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"plan" text DEFAULT 'free' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_accounts_plan_valid" CHECK ("loupe_accounts"."plan" in ('free', 'indie', 'pro', 'studio'))
);
--> statement-breakpoint
ALTER TABLE "loupe_accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_card_luts" (
	"project_id" bigint NOT NULL,
	"card" text NOT NULL,
	"lut_id" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_card_luts_project_id_card_pk" PRIMARY KEY("project_id","card")
);
--> statement-breakpoint
ALTER TABLE "loupe_card_luts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_files" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "loupe_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" bigint NOT NULL,
	"card" text DEFAULT '' NOT NULL,
	"path" text NOT NULL,
	"storage_key" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"last_modified_ms" bigint,
	"is_video" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"problem" text,
	"upload_id" text,
	"uploaded_at" timestamp with time zone,
	"uploaded_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_files_storage_key_unique" UNIQUE("storage_key"),
	CONSTRAINT "loupe_files_status_valid" CHECK ("loupe_files"."status" in ('pending', 'uploading', 'uploaded', 'unreadable')),
	CONSTRAINT "loupe_files_size_valid" CHECK ("loupe_files"."size_bytes" >= 0)
);
--> statement-breakpoint
ALTER TABLE "loupe_files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_luts" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "loupe_luts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_id" bigint NOT NULL,
	"name" text NOT NULL,
	"storage_key" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"cube_size" integer NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_luts_storage_key_unique" UNIQUE("storage_key")
);
--> statement-breakpoint
ALTER TABLE "loupe_luts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_members" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "loupe_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_id" bigint NOT NULL,
	"email" text NOT NULL,
	"role" text DEFAULT 'owner' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_members_email_unique" UNIQUE("email"),
	CONSTRAINT "loupe_members_email_lowercase" CHECK ("loupe_members"."email" = lower("loupe_members"."email")),
	CONSTRAINT "loupe_members_role_valid" CHECK ("loupe_members"."role" in ('owner', 'editor', 'director', 'viewer'))
);
--> statement-breakpoint
ALTER TABLE "loupe_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_projects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "loupe_projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1001 CACHE 1),
	"account_id" bigint NOT NULL,
	"name" text NOT NULL,
	"shoot_date" date NOT NULL,
	"storage_prefix" text NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"uploaded_at" timestamp with time zone,
	"lut_id" bigint,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_projects_storage_prefix_unique" UNIQUE("storage_prefix"),
	CONSTRAINT "loupe_projects_status_valid" CHECK ("loupe_projects"."status" in ('scheduled', 'uploading', 'uploaded', 'delivered', 'purged'))
);
--> statement-breakpoint
ALTER TABLE "loupe_projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_proxy_jobs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "loupe_proxy_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"raw_key" text NOT NULL,
	"proxy_key" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 4 NOT NULL,
	"run_after" timestamp with time zone DEFAULT now() NOT NULL,
	"locked_by" text,
	"locked_at" timestamp with time zone,
	"progress" real,
	"error" text,
	"proxy_size_bytes" bigint,
	"preview_size_bytes" bigint,
	"media" jsonb,
	"lut_id" bigint,
	"made_with_lut_id" bigint,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "loupe_proxy_jobs_file_id_unique" UNIQUE("file_id"),
	CONSTRAINT "loupe_proxy_jobs_proxy_key_unique" UNIQUE("proxy_key"),
	CONSTRAINT "loupe_proxy_jobs_status_valid" CHECK ("loupe_proxy_jobs"."status" in ('queued', 'running', 'done', 'failed', 'skipped'))
);
--> statement-breakpoint
ALTER TABLE "loupe_proxy_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loupe_sign_in_attempts" (
	"email" text PRIMARY KEY NOT NULL,
	"failures" integer DEFAULT 0 NOT NULL,
	"window_start" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "loupe_sign_in_attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "loupe_card_luts" ADD CONSTRAINT "loupe_card_luts_project_id_loupe_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."loupe_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_card_luts" ADD CONSTRAINT "loupe_card_luts_lut_id_loupe_luts_id_fk" FOREIGN KEY ("lut_id") REFERENCES "public"."loupe_luts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_files" ADD CONSTRAINT "loupe_files_project_id_loupe_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."loupe_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_luts" ADD CONSTRAINT "loupe_luts_account_id_loupe_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."loupe_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_members" ADD CONSTRAINT "loupe_members_account_id_loupe_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."loupe_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_projects" ADD CONSTRAINT "loupe_projects_account_id_loupe_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."loupe_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_projects" ADD CONSTRAINT "loupe_projects_lut_id_loupe_luts_id_fk" FOREIGN KEY ("lut_id") REFERENCES "public"."loupe_luts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_proxy_jobs" ADD CONSTRAINT "loupe_proxy_jobs_file_id_loupe_files_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."loupe_files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_proxy_jobs" ADD CONSTRAINT "loupe_proxy_jobs_project_id_loupe_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."loupe_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loupe_proxy_jobs" ADD CONSTRAINT "loupe_proxy_jobs_lut_id_loupe_luts_id_fk" FOREIGN KEY ("lut_id") REFERENCES "public"."loupe_luts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "loupe_files_project_path_idx" ON "loupe_files" USING btree ("project_id","path");--> statement-breakpoint
CREATE INDEX "loupe_files_project_card_idx" ON "loupe_files" USING btree ("project_id","card");--> statement-breakpoint
CREATE INDEX "loupe_luts_account_idx" ON "loupe_luts" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "loupe_members_account_idx" ON "loupe_members" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "loupe_projects_account_idx" ON "loupe_projects" USING btree ("account_id","shoot_date");--> statement-breakpoint
CREATE INDEX "loupe_proxy_jobs_queue_idx" ON "loupe_proxy_jobs" USING btree ("status","run_after");--> statement-breakpoint
CREATE INDEX "loupe_proxy_jobs_project_idx" ON "loupe_proxy_jobs" USING btree ("project_id");--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_accounts" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_card_luts" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_files" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_luts" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_members" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_projects" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_proxy_jobs" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "loupe_app_all" ON "loupe_sign_in_attempts" AS PERMISSIVE FOR ALL TO "loupe_app" USING (true) WITH CHECK (true);--> statement-breakpoint
-- The app and worker only read and write rows in these tables.
GRANT USAGE ON SCHEMA "public" TO "loupe_app";--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "loupe_accounts", "loupe_card_luts", "loupe_files", "loupe_luts", "loupe_members", "loupe_projects", "loupe_proxy_jobs", "loupe_sign_in_attempts" TO "loupe_app";--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE "loupe_accounts_id_seq", "loupe_files_id_seq", "loupe_luts_id_seq", "loupe_members_id_seq", "loupe_projects_id_seq", "loupe_proxy_jobs_id_seq" TO "loupe_app";--> statement-breakpoint
-- No access through Supabase's public API, even if row-level security were ever switched off.
REVOKE ALL ON "loupe_accounts", "loupe_card_luts", "loupe_files", "loupe_luts", "loupe_members", "loupe_projects", "loupe_proxy_jobs", "loupe_sign_in_attempts" FROM "anon", "authenticated";
